# Generated by Django 2.1.15 on 2021-11-05 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_recipe_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
